Repository ScoopInstaller/Extras, pull requests merged in 2020-09, with the labels that each got.

#4707 Update darktable.json with latest NSIS exe file
  bucket/darktable.json
Labels: please-review, review-needed

#4753 wexond: Fix manifest
  bucket/wexond.json
Labels: review-needed

#4752 musicbee: Fix license
  bucket/musicbee.json
Labels: package-fix-needed
