Repository ScoopInstaller/Extras, pull requests merged in 2020-12, with the labels that each got.

#5279 imageglass: Update to version 8.0.12.8
  bucket/imageglass.json
Labels: review-needed

#5278 workspacer: Add version 0.9.9
  bucket/workspacer.json
Labels: review-needed

#5268 plantuml: Fix shim parameters handling.
  bucket/plantuml.json
Labels: package-fix-needed

#5232 cura@4.8.0: Fix URL
  bucket/cura.json
Labels: package-fix-needed, waiting-feedback
