Repository ScoopInstaller/Extras, pull requests merged in 2020-06, with the labels that each got.

#4185 simplewall: Persist profile.xml
  bucket/simplewall.json
Labels: package-fix-needed, review-needed

#4195 freedownloadmanager: Update to version 6.10.0
  bucket/freedownloadmanager.json
Labels: package-fix-needed

#4280 Handbrake: Update to version 1.3.3
  bucket/handbrake.json
Labels: review-needed

#4306 vcredist(2019|2019-portable): Update to version 14.26.28720.3
  bucket/vcredist.json
  bucket/vcredist2019-portable.json
  bucket/vcredist2019.json
Labels: review-needed

#4343 cabal: Add hash extraction
  bucket/cabal.json
Labels: review-needed

#4342 ripcord: Add version 0.4.26
  bucket/ripcord.json
Labels: review-needed
