Repository ScoopInstaller/Extras, pull requests merged in 2020-11, with the labels that each got.

#5035 nirlauncher: Add new .exes
  bucket/nirlauncher.json
Labels: review-needed

#5048 archwsl: Don’t erase file system on upgrades
  bucket/archwsl.json
Labels: review-needed

#5090 netch: Fix default configuration
  bucket/netch.json
Labels: package-fix-needed

#5132 xmousebuttoncontrol: Update to version 2.19.2
  bucket/xmousebuttoncontrol.json
Labels: package-fix-needed

#5151 qv2ray: Make v2ray dependency optional
  bucket/qv2ray.json
Labels: package-fix-needed

#5197 anaconda3: Update to version 2020.11
  bucket/anaconda3.json
Labels: review-needed

#4918 deepgit: Removing 32bit architecture
  bucket/deepgit.json
Labels: review-needed, waiting-feedback

#5209 windiff: Add version 2.1.0
  bucket/windiff.json
Labels: review-needed
