Repository ScoopInstaller/Extras, pull requests merged in 2020-07, with the labels that each got.

#4394 keepassxc@2.6.0: Persist config folder
  bucket/keepassxc.json
Labels: package-fix-needed

#4392 ilspy: Update to version 6.0.0.5836
  bucket/ilspy.json
Labels: review-needed

#4426 android-sdk: Persist system-images
  bucket/android-sdk.json
Labels: waiting-feedback
