Repository ScoopInstaller/Extras, pull requests merged in 2021-11, with the labels that each got.

#7195 Update cpu-z.json
  bucket/cpu-z.json
Labels: package-fix-needed

#7200 diagram-designer: Add version 1.29.5
  bucket/diagram-designer.json
Labels: review-needed, discussion

#6916 youtubedownloader: Add version 1.8.3
  bucket/youtubedownloader.json
Labels: package-fix-needed, discussion

#6674 vapoursyntheditor: Add version 19
  bucket/vapoursyntheditor.json
Labels: review-needed

#7213 Add autoupdate to paint.net
  bucket/paint.net.json
Labels: package-fix-needed

#7212 Update makehuman manifest
  bucket/makehuman.json
Labels: review-needed

#7201 grepWin: Add checkver for automated updates
  bucket/grepwin.json
Labels: review-needed

#7217 Add postinstall to remove autoupdate file
  bucket/bitwarden.json
Labels: review-needed

#6017 tomcat: Persist conf and webapps folders
  bucket/tomcat.json
Labels: review-needed

#5224 archwsl: Prevents installation outside Scoop management
  bucket/archwsl.json
Labels: package improvement

#7228 wincrypt-sshagent: Add version 1.1.9
  bucket/wincrypt-sshagent.json
Labels: new package

#7205 add context menu handlers for lockhunter
  bucket/lockhunter.json
  scripts/lockhunter/install-context.reg
  scripts/lockhunter/uninstall-context.reg
Labels: review-needed, package improvement

#6505 manjarowsl: Add version 20211101
  bucket/manjarowsl.json
Labels: review-needed, new package

#7232 gimp: Update to version 2.10.28
  bucket/gimp.json
Labels: package update

#7225 fix(script): use `scoop prefix` to correctly find scoop's path
  bin/auto-pr.ps1
  bin/checkurls.ps1
  bin/checkver.ps1
  bin/formatjson.ps1
  bin/missing-checkver.ps1
  bin/test.ps1
Labels: enhancement

#3625 xampp: Add version 8.0.12-0
  bucket/xampp.json
Labels: review-needed, new package

#6584 foxit-reader: Deprecate manifest in favour of foxit-pdf-reader
  bucket/foxit-reader.json
Labels: package update, discussion

#6585 foxit-pdf-reader: Add version 11.0.1.49938
  bucket/foxit-pdf-reader.json
Labels: package update

#7246 CapFrameX: fix autoupdate extract_dir
  bucket/capframex.json
Labels: review-needed

#7209 sdl2-image: Add version 2.0.5
  bucket/sdl2-image.json
Labels: new package

#7173 Merge qbittorrent-portable into qbittorrent
  bucket/qbittorrent.json
Labels: waiting feedback, discussion

#7250 nirlauncher: Update via nlp2json.py
  bucket/nirlauncher.json
Labels: review-needed

#7254 siyuan-note: Add version 1.4.8
  bucket/siyuan-note.json
Labels: review-needed

#6451 virt-viewer: Add version 10.0-1.0
  bucket/virt-viewer.json
Labels: package-fix-needed, new package

#7230 ilspy: update to 7.1.0.6543
  bucket/ilspy.json
Labels: package update, review-needed

#7184 bizhawk: Persist 'NDS' and 'Melon' folders
  bucket/bizhawk.json
Labels: review-needed, package improvement

#7272 kitty: Update homepage in manifest.
  bucket/kitty.json
Labels: review-needed

#7255 chromium: Update to version 95.0.4638.69-r920003-1
  bucket/chromium.json
Labels: review-needed

#7273 netron: Update homepage
  bucket/netron.json
Labels: review-needed

#7282 ungoogled-chromium-portable: Fix manifest and update
  bucket/ungoogled-chromium-portable.json
Labels: review-needed

#7293 powertoys: update to 0.49.1
  bucket/powertoys.json
Labels: review-needed

#7294 lazygit: Update to version 0.31.3
  bucket/lazygit.json
Labels: review-needed

#7296 ventoy: Update to version 1.0.59
  bucket/ventoy.json
Labels: review-needed

#7284 neovim-qt: Add version 0.2.16.1
  bucket/fvim.json
  bucket/neovim-qt.json
Labels: review-needed

#7301 lite-xl: Add version 2.0.3
  bucket/lite-xl.json
  bucket/lite.json
Labels: review-needed

#7314 Update Ventoy to 1.0.60
  bucket/ventoy.json
Labels: review-needed

#3976 tuxguitar: Add version 1.5.4
  bucket/tuxguitar.json
Labels: new package

#7318 Update Brave Browser version
  bucket/brave.json
Labels: review-needed

#6391 git-credential-manager-core: Add version 2.0.567.18224
  bucket/git-credential-manager-core.json
Labels: new package

#7325 openark: Update to version 1.2.0
  bucket/openark.json
Labels: review-needed

#7329 Ventoy: Update to 1.0.61
  bucket/ventoy.json
Labels: review-needed

#7332 Fix old path in vscode-insiders.json that was blocking installation
  bucket/vscode-insiders.json
Labels: review-needed

#6642 colorcontrol: Add version 4.1.0.0
  bucket/colorcontrol.json
Labels: new package

#7343 Update the checkver URL for firefox-beta as no updates were available anymore
  bucket/firefox-beta.json
Labels: review-needed

#6581 mpc-hc-fork: persist default.mpcpl like mpc-be.json does it
  bucket/mpc-hc-fork.json
Labels: package improvement

#7339 bat2exe: Add version 2.0
  bucket/bat2exe.json
Labels: new package

#7346 bt (Browser Tamer): Add version 2.1
  bucket/bt.json
Labels: new package

#6347 zoom: register/unregister zoommtg:// protocol handler
  bucket/zoom.json
Labels: package-fix-needed, package improvement

#7014 xnconvert: Add version 1.94
  bucket/xnconvert.json
Labels: package-fix-needed

#7351 grepwin: Rename .reg files
  bucket/grepwin.json
  scripts/grepwin/install-context.reg
  scripts/grepwin/uninstall-context.reg
Labels: package improvement

#7352 update rocket-chat desktop client to 3.6.0
  bucket/rocketchat-client.json
Labels: review-needed

#6529 ghidra: Add version 10.0.4-20210928
  bucket/ghidra.json
Labels: review-needed, new package

#7360 linqpad: Update to 7.1.4
  bucket/linqpad.json
Labels: review-needed

#6469 V2RayN: Update manifest to support Xray-core
  bucket/v2rayn.json
Labels: package-fix-needed, review-needed, package improvement

#7354 revouninstaller: Add version 2.3.5
  bucket/revouninstaller.json
Labels: review-needed, new package

#6305 qownnotes: Add version 21.6.1
  bucket/qownnotes.json
Labels: review-needed, new package

#7367 logseq: update to 0.4.9
  bucket/logseq.json
Labels: review-needed

#7368 flameshot: Fix "extract_dir"
  bucket/flameshot.json
Labels: review-needed

#7376 vscodium, vscodium-portable: update to 1.62.3
  bucket/vscodium-portable.json
  bucket/vscodium.json
Labels: review-needed

#7373 Update firefox.json: v94.0.2
  bucket/firefox.json
Labels: review-needed

#7377 rainmeter: Update to version 4.5.5.3565
  bucket/rainmeter.json
Labels: review-needed

#7378 rainmeter-portable: Update to version 4.5.5.3565
  bucket/rainmeter-portable.json
Labels: review-needed

#7384 taskbarx: Update to version 1.7.3.0
  bucket/taskbarx.json
Labels: review-needed

#7385 notepadplusplus: Update to version 8.1.9.2
  bucket/notepadplusplus.json
Labels: review-needed

#7386 paint.net: Update to version 4.3.3
  bucket/paint.net.json
Labels: review-needed

#6172 tachidesk-server: Add version 0.4.5
  bucket/tachidesk-server.json
  scripts/tachidesk-server/tachidesk-debug.ps1
  scripts/tachidesk-server/tachidesk-electron.ps1
  scripts/tachidesk-server/tachidesk.ps1
Labels: package-fix-needed, new package

#6670 aegisubdc: Add version 9214
  bucket/aegisubdc.json
Labels: new package

#7390 winrar: Add 'helper' package
  bucket/winrar-helper.json
Labels: discussion

#7396 horcrux: Add version 0.2
  bucket/horcrux.json
Labels: review-needed

#7397 Add GeoGebra version 6.0.676.0
  bucket/geogebra.json
Labels: review-needed

#7398 logseq: update to 0.5.0
  bucket/logseq.json
Labels: review-needed

#7400 trilium: Add persistent data
  bucket/trilium.json
Labels: review-needed

#7403 Update ScreenToGif to 2.34.1
  bucket/screentogif.json
Labels: review-needed

#7404 Update hydrus-network to 463
  bucket/hydrus-network.json
Labels: review-needed

#7409 logseq: update to 0.5.1
  bucket/logseq.json
Labels: review-needed

#7413 imageglass: Update to version 8.3.11.21
  bucket/imageglass.json
Labels: review-needed

#7424 lazygit: Update To version 0.31.4
  bucket/lazygit.json
Labels: review-needed

#7426 telegram: add x64 version
  bucket/telegram.json
Labels: review-needed

#5036 paperwork: Add version 2.0
  bucket/paperwork.json
Labels: package-fix-needed, new package

#7432 shotcut: update to v21.10.31
  bucket/shotcut.json
Labels: review-needed

#7434 Shotcut: Fix install
  bucket/shotcut.json
Labels: review-needed

#7435 pcem: Change to http URLs
  bucket/pcem.json
Labels: review-needed

#7427 languagetool-electron: Add version 1.0.4
  bucket/languagetool-java.json
  bucket/languagetool.json
Labels: review-needed

#7430 emule-community: update to 0.60d; add x64 architecture
  bucket/emule-community.json
Labels: review-needed

#1730 castle-view-image: Add version 2.0.0
  bucket/castle-view-image.json
Labels: review-needed

#7445 Update tachidesk-server.json and change autoupdate logic
  bucket/tachidesk-server.json
Labels: review-needed
