Repository ScoopInstaller/Extras, pull requests merged in 2021-01, with the labels that each got.

#5413 vcredist: Adjust description (#5413) [scoop skip]
  bucket/vcredist.json
Labels: package-fix-needed

#5477 openshot: Use native executable as shortcut target
  bucket/openshot.json
Labels: package-fix-needed

#5431 streamlink: Update to version 2.0.0
  bucket/streamlink.json
Labels: review-needed

#5179 alacritty: Update to version 0.7.1
  bucket/alacritty.json
Labels: review-needed, waiting-feedback

#5529 kicad-lite: Add version 5.1.9_1
  bucket/kicad-lite.json
Labels: review-needed

#5521 privatezilla: Add version 0.43.0
  bucket/privatezilla.json
Labels: review-needed

#5514 syncthingtray: Add version 1.1.1
  bucket/syncthingtray.json
Labels: review-needed

#5510 picgo: Add version 2.2.2
  bucket/picgo.json
Labels: review-needed

#5470 winauth: portable configuration
  bucket/winauth.json
Labels: review-needed

#5377 Update paint.net-plugin-pyrochild.json
  bucket/paint.net-plugin-pyrochild.json
Labels: review-needed

#5548 php(-nts)-xdebug: Update to version 3.0.2-8.0
  bucket/php-nts-xdebug.json
  bucket/php-xdebug.json
Labels: review-needed

#5513 onlyoffice-desktopeditors: Update to version 6.1.0.90
  bucket/onlyoffice-desktopeditors.json
Labels: review-needed
