Repository ScoopInstaller/Extras, pull requests merged in 2021-12, with the labels that each got.

#7447 renderdoc: update to 1.17
  bucket/renderdoc.json
Labels: review-needed

#6100 manifold: Add version 9.0.175
  bucket/manifold.json
Labels: review-needed, new package

#6099 manifold-viewer: Add version 9.0.174.2
  bucket/manifold-viewer.json
Labels: review-needed, new package

#6639 tachidesk-jui: Add version 1.2.0
  bucket/tachidesk-jui.json
Labels: review-needed, new package

#7453 Update rainmeter.json
  bucket/rainmeter.json
Labels: review-needed

#7454 Update rainmeter-portable.json
  bucket/rainmeter-portable.json
Labels: review-needed

#7455 quicklook: Update to version 3.7.1
  bucket/quicklook.json
Labels: review-needed

#7460 Add SolveSpace version 3.0
  bucket/solvespace.json
Labels: review-needed

#3844 various: homepage fixes
  bucket/bgpkiller.json
  bucket/echoargs.json
  bucket/soundnode.json
Labels: enhancement

#7487 Monero: Fix hash
  bucket/monero.json
Labels: review-needed

#7491 Swapped yt-dlg to the maintained fork by @oleksis
  bucket/youtube-dl-gui.json
Labels: review-needed

#7492 sdl2: update to 2.0.18
  bucket/sdl2.json
Labels: review-needed

#7481 eclipse-embedcpp: Add version 2021-09
  bucket/eclipse-embedcpp.json
Labels: review-needed

#6237 mucommander: Add version 0.9.7-1
  bucket/mucommander.json
Labels: package-fix-needed, waiting feedback, review-needed, new package

#7493 tabby: Add au.hash and fix homepage
  bucket/tabby.json
Labels: review-needed

#6029 cherrytree: Update to version 0.99.44.0
  bucket/cherrytree.json
Labels: package update, review-needed

#4842 glimpse: Add version 0.2.0
  bucket/glimpse.json
Labels: package-fix-needed, new package

#7486 Add Microsoft Teams
  bucket/microsoft-teams.json
Labels: review-needed

#7520 Update msiafterburner.json: Corrects version in the manifest
  bucket/msiafterburner.json
Labels: review-needed

#6786 Pyzo: Add version 4.11.7
  bucket/pyzo.json
Labels: package-fix-needed, new package

#7525 free-manga-downloader-2: Add version 2.0.31.0
  bucket/free-manga-downloader2.json
Labels: review-needed

#4357 webcopy: Add version 1.8.0.652
  bucket/webcopy.json
Labels: package-fix-needed, review-needed, new package

#1497 pidgin: Add version 2.14.8
  bucket/pidgin.json
Labels: review-needed, discussion, new package

#7531 php(-nts)-xdebug: Update to version 3.1.2-8.1
  bucket/php-nts-xdebug.json
  bucket/php-xdebug.json
Labels: review-needed

#5987 TortoiseHg for mercurial
  bucket/tortoisehg.json
Labels: package-fix-needed, review-needed, new package

#7534 vcredist: Update to vcredist2022
  bucket/vcredist.json
Labels: review-needed, discussion

#7539 vcredist packages: Add text for exit codes
  bucket/vcredist.json
  bucket/vcredist2005.json
  bucket/vcredist2008.json
  bucket/vcredist2010.json
  bucket/vcredist2012.json
  bucket/vcredist2013.json
  bucket/vcredist2015.json
  bucket/vcredist2017.json
  bucket/vcredist2019.json
  bucket/vcredist2022.json
Labels: review-needed

#7536 LibreSprite: Add version 1.0
  bucket/libresprite.json
Labels: review-needed

#2173 Add DisplayCAL and ArgyllCMS
  bucket/argyllcms.json
  bucket/displaycal.json
Labels: review-needed, new package

#7540 onecommander: add version 3.4.2.0
  bucket/onecommander.json
Labels: review-needed

#7545 Switch standardnotes to x64
  bucket/standardnotes.json
Labels: review-needed

#7547 IntegerScaler: add version 2.18
  bucket/integerscaler.json
Labels: review-needed

#7549 qt-creator: Add version 6.0.1
  bucket/qt-creator.json
Labels: review-needed

#7550 enable back ThrottleStop
  bucket/throttlestop.json
Labels: review-needed

#7353 mtuner: Add version 4.4.8
  bucket/mtuner.json
Labels: review-needed, new package

#7552 Create autohdr.json: For Codectory's AutoHDR project
  bucket/autohdr.json
Labels: review-needed

#7554 Added file type icon association support to VSCode and its variations
  bucket/vscode-insiders-portable.json
  bucket/vscode-insiders.json
  bucket/vscode-portable.json
  bucket/vscode.json
  bucket/vscodium-portable.json
  bucket/vscodium.json
  scripts/vscode/install-associations.reg
  scripts/vscode/uninstall-associations.reg
Labels: review-needed

#7501 GSmartControl: add version 1.1.3
  bucket/gsmartcontrol.json
Labels: review-needed

#7566 renamer: Fix license
  bucket/renamer.json
Labels: review-needed

#7576 tinymediamanager: Version up to 4.2.4, fix download url, add autoupdate.
  bucket/tinymediamanager.json
Labels: review-needed

#7570 gpxsee: Add version 10.0
  bucket/gpxsee.json
Labels: review-needed

#7581 zoom: Update to version 5.9.0.2481
  bucket/zoom.json
Labels: review-needed

#7583 vcredist2022: Update to 14.31.30919
  bucket/vcredist.json
  bucket/vcredist2022-portable.json
  bucket/vcredist2022.json
Labels: review-needed

#7584 Create w10privacy.json
  bucket/w10privacy.json
Labels: review-needed

#5749 w64devkit: Add version 1.10.0
  bucket/w64devkit.json
Labels: review-needed, new package

#5628 scoop-completion: Add version 0.2.3
  bucket/scoop-completion.json
Labels: review-needed, new package

#6637 activemq: Add version 5.16.2
  bucket/activemq.json
Labels: new package

#7591 compatibility-manager: Add version 1.1.2
  bucket/compatibility-manager.json
Labels: review-needed

#7590 superf4: Add version 1.4
  bucket/superf4.json
Labels: review-needed

#7594 video-compare: Add version 20211223
  bucket/video-compare.json
Labels: review-needed

#7578 proxifier-portable: Update to version 4.07
  bucket/proxifier-portable.json
Labels: review-needed

#4245 search-deflector: Add version 1.3.2
  bucket/search-deflector.json
Labels: new package

#7601 schismtracker: Update to version 20211116
  bucket/schismtracker.json
Labels: review-needed

#7586 Update Inkscape to 1.1.1 and fix autoupdate
  bucket/inkscape.json
Labels: review-needed

#7599 mongodb-compass: Add version 1.29.6
  bucket/mongodb-compass-community.json
  bucket/mongodb-compass.json
Labels: review-needed

#7602 Cuetools: Update to version 2.1.9
  bucket/cuetools.json
Labels: review-needed

#7585 wsa-pacman: Add version 1.1.1
  bucket/wsa-pacman.json
  scripts/wsa-pacman/install-associations.reg
  scripts/wsa-pacman/uninstall-associations.reg
Labels: review-needed

#7317 ryzen-controller: Add version 2.5.4
  bucket/ryzen-controller.json
Labels: review-needed, new package

#6452 cv4pve-pepper: Add version 1.5.0
  bucket/cv4pve-pepper.json
Labels: review-needed, new package

#6284 aws-session-manager-plugin: Add version 1.2.54.0
  bucket/aws-session-manager-plugin.json
Labels: review-needed, new package

#6728 cupscale: Add version 1.39.0f1
  bucket/cupscale.json
Labels: review-needed, new package

#6824 syncplay: Add version 1.6.9
  bucket/syncplay.json
Labels: package-fix-needed, review-needed, new package

#7609 gb-studio: Update to version 3.0.2
  bucket/gb-studio.json
Labels: review-needed

#7616 fileoptimizer@15.20.2657: Fix hash
  bucket/fileoptimizer.json
Labels: review-needed

#6729 add goneovim
  bucket/goneovim.json
Labels: package-fix-needed, review-needed, new package

#7613 thsiswin11: Add version 1.0.50
  bucket/thisiswin11.json
Labels: review-needed

#6841 librehardwaremonitor: Add version 0.8.8
  bucket/librehardwaremonitor.json
Labels: review-needed, new package

#6673 avspmod: Add version 2.6.9.0
  bucket/avspmod.json
Labels: test-needed, new package

#7303 impregnate: Add version 1.2.2
  bucket/impregnate.json
Labels: review-needed, new package

#6574 roundedtb: Add version R2.2
  bucket/roundedtb.json
Labels: package-fix-needed, review-needed, new package

#5564 biblioteq: Add version 2021.02.12
  bucket/biblioteq.json
Labels: package-fix-needed, review-needed, new package

#7612 ultravnc: Add version 1.3.6.0
  bucket/ultravnc.json
Labels: review-needed

#1335 zerobrane-studio: Add version 1.80
  zerobrane-studio.json
Labels: help-wanted, new package

#3028 uget-portable:Add persistence
  bucket/uget-portable.json
Labels: package improvement

#2065 keepass-plugin-keepasshttp: Add version 1.8.4.2
  bucket/keepass-plugin-keepasshttp.json
Labels: package-fix-needed, review-needed, new package

#2729 winscp: add commandline-friendly binary.
  bucket/winscp.json
Labels: package improvement

#7625 red: add version 2.2
  bucket/red.json
Labels: review-needed

#5166 folding-at-home: Add version 7.6.21
  bucket/folding-at-home.json
Labels: new package

#5094 roslynpad: Add version 15.1
  bucket/roslynpad.json
Labels: new package

#5064 shadowsocks-v2ray-plugin: Add version 1.3.1
  bucket/shadowsocks-v2ray-plugin.json
Labels: new package

#7606 netbeans: Update to version 12.6
  bucket/netbeans.json
Labels: review-needed

#5229 Set default grafana-server homepath
  bucket/grafana.json
Labels: package improvement

#5012 macrocreator: Add version 5.3.2
  bucket/macrocreator.json
Labels: new package

#3609 xmind: Add version 11.1.2
  bucket/xmind.json
  bucket/xmind8.json
Labels: review-needed, new package

#7630 ubports-installer: Add version 0.9.1-beta
  bucket/ubports-installer.json
Labels: review-needed

#5020 qtscrcpy: Add version 1.4.5
  bucket/qtscrcpy.json
Labels: package-fix-needed, waiting feedback, review-needed, new package

#7631 xmlnotepad: Add version 2.8.0.52
  bucket/xmlnotepad.json
Labels: review-needed

#7620 buckets: Add version 0.63.2
  bucket/buckets.json
Labels: review-needed

#7573 (chore): Use portable configurations by default
  bucket/arduino-portable.json
  bucket/arduino.json
  bucket/firefox-esr-portable.json
  bucket/firefox-esr.json
  bucket/firefox-portable.json
  bucket/firefox.json
  bucket/foobar2000-portable.json
  bucket/foobar2000.json
  bucket/googlechrome-portable.json
  bucket/googlechrome.json
  bucket/gpg4win-portable.json
  bucket/palemoon-portable.json
  bucket/palemoon.json
  bucket/proxifier.json
  bucket/qtox-portable.json
  bucket/qtox.json
  bucket/rainmeter-portable.json
  bucket/rainmeter.json
  bucket/streamlink-portable.json
  bucket/streamlink.json
  bucket/strokesplus.json
  bucket/thunderbird-portable.json
  bucket/thunderbird.json
  bucket/uget-portable.json
  bucket/uget.json
  bucket/ungoogled-chromium-portable.json
  bucket/ungoogled-chromium.json
  bucket/vcredist2012-portable.json
  bucket/vcredist2013-portable.json
  bucket/vcredist2015-portable.json
  bucket/vcredist2017-portable.json
  bucket/vcredist2019-portable.json
  bucket/vcredist2022-portable.json
  bucket/vscode-portable.json
  bucket/vscode.json
  bucket/vscodium-portable.json
  bucket/vscodium.json
Labels: review-needed

#7632 jpegview: Manually persist 'ParamDB.db'
  bucket/jpegview.json
Labels: review-needed

#4806 trillian: Add version 6.4.0.5
  bucket/trillian.json
Labels: package-fix-needed, review-needed, new package, blocked

#4311 toggl: Add version 7.5.363
  bucket/toggl.json
Labels: review-needed, new package

#4386 xenu: Add version 1.3.8
  bucket/xenu.json
Labels: package-fix-needed, review-needed, new package

#7635 manifold: fix autoupdate
  bucket/manifold.json
Labels: review-needed

#7634 manifold-viewer: fix autoupdate
  bucket/manifold-viewer.json
Labels: review-needed

#7638 toggl: Update to version 7.5.445, fix checkver
  bucket/toggl.json
Labels: review-needed

#7637 freecad: Fix autoupdate and update to latest
  bucket/freecad.json
Labels: review-needed

#5387 jstock: Add version 1.0.7.45
  bucket/jstock.json
Labels: package-fix-needed, review-needed, new package

#7636 JMkvpropedit: Add version 1.5.2
  bucket/jmkvpropedit.json
Labels: review-needed

#7633 onecommander: Fix license URL and checkver and persist templates
  bucket/onecommander.json
Labels: review-needed

#7629 dxwnd: Add version 2.05.78
  bucket/dxwnd.json
Labels: review-needed

#4226 fiddler: Make the script editor work
  bucket/fiddler.json
Labels: review-needed, test-needed, package improvement

#4165 totalcommander@9.51: Update persist
  bucket/totalcommander.json
Labels: package improvement

#3865 coreftp: Add version 2.2
  bucket/coreftp.json
Labels: waiting feedback, review-needed, new package

#3975 handbrake: Use portable configuration
  bucket/handbrake.json
Labels: package improvement
