Repository ScoopInstaller/Extras, pull requests merged in 2022-10, with the labels that each got.

#8153 scoop-sd: Add version 0.3
  bucket/scoop-sd.json
Labels: review-needed

#9375 adding more Sordum apps to the official bucket
  bucket/backup-start-menu-layout.json
  bucket/desktop-ini-editor.json
  bucket/drive-letter-changer.json
  bucket/easy-context-menu.json
  bucket/host-editor.json
  bucket/network-profile-name-changer.json
  bucket/reicon.json
  bucket/runastool.json
  bucket/sendto-menu-editor.json
  bucket/show-disk-partition-style.json
  bucket/webcam-on-off.json
  bucket/windows11-classic-context-menu.json
Labels: review-needed

#9338 spotify-qt: Add version 3.9
  bucket/spotify-qt.json
Labels: review-needed

#9446 everything: Uninstall if service is not installed
  bucket/everything.json
Labels: review-needed

#9371 Scoop-completion: fix script error
  bucket/scoop-completion.json
Labels: review-needed

#9473 nefcon: Add arm64 architecture
  bucket/nefcon.json
Labels: review-needed

#9472 typioca: Add arm64 architecture
  bucket/typioca.json
Labels: review-needed

#9471 moonlight: Add arm64 architecture
  bucket/moonlight.json
Labels: review-needed

#9478 wireshark: Update to version 4.0.0
  bucket/wireshark.json
Labels: review-needed

#9449 git-tower: Add version 4.0.410
  bucket/git-tower.json
Labels: review-needed

#9490 privacy.sexy: Add version 0.11.4
  bucket/privacy.sexy.json
Labels: review-needed

#9489 zoom: Add a different `pre_install` script for each architecture
  bucket/zoom.json
Labels: review-needed

#9488 musikcube: Fix bin
  bucket/musikcube.json
Labels: review-needed

#9453 hydrus-network: Update to version 502
  bucket/hydrus-network.json
Labels: review-needed

#9467 strokeplus.net: Fix pre_install and persist
  bucket/strokesplus.net.json
Labels: review-needed

#9320 qrscan: Fix `extract_dir` error
  bucket/qrscan.json
Labels: review-needed

#9282 elasticsearch: Use `bin` path to avoid missing shims for older versions
  bucket/elasticsearch.json
Labels: review-needed

#9325 youtube-music: Fix url and autoupdate
  bucket/youtube-music.json
Labels: review-needed

#9330 musicplayer2@2.75: Set portable mode to default configuration
  bucket/musicplayer2.json
Labels: review-needed

#9437 avidemux: Update to version 2.8.1
  bucket/avidemux.json
Labels: review-needed

#9498 veusz: Fix `pre_install` script error. Also fix `checkver`
  bucket/veusz.json
Labels: review-needed

#9500 nekoray: Add version 1.13
  bucket/nekoray.json
Labels: review-needed

#9317 sidekick-browser: add version 104.29.3.25043-e335c0c
  bucket/sidekick-browser.json
Labels: review-needed

#9434 hashcheck: Enhance the `installer` and `uninstaller` scripts.
  bucket/hashcheck.json
Labels: review-needed

#9484 ungoogled-chromium: Update manifest
  bucket/ungoogled-chromium.json
Labels: review-needed

#9550 aegisubdc: Update to version 9215 and fix checkver
  bucket/aegisubdc.json
Labels: review-needed

#9520 handbrake: Remove unneeded `"depends"` property
  bucket/handbrake.json
Labels: review-needed

#9541 spotube: Fix `autoupdate.url` and `autoupdate.hash.regex`
  bucket/spotube.json
Labels: review-needed

#9521 pacaptr: Add version 0.16.1
  bucket/pacaptr.json
Labels: review-needed

#9412 cinny: Add version 2.2.2
  bucket/cinny.json
Labels: review-needed

#9347 wpd: add version 1.5.2042
  bucket/wpd.json
Labels: review-needed

#9192 onboard-memory-manager: Add version 1.1.6805
  bucket/logitech-omm.json
Labels: review-needed, discussion, not ready

#9558 catalyst: Add version 3.2.2
  bucket/catalyst.json
Labels: review-needed

#9455 famistudio: Add version 4.0.4
  bucket/famistudio.json
Labels: review-needed

#9570 armips: Add version 0.11.0
  bucket/armips.json
Labels: review-needed

#9578 nwjs-sdk@0.69.1: Fix `bin`
  bucket/nwjs-sdk.json
Labels: review-needed

#9577 tutanota: Add version 3.102.3
  bucket/tutanota.json
Labels: review-needed

#9580 privacy.sexy: Update `audoupdate`
  bucket/privacy.sexy.json
Labels: review-needed

#9579 tutanota: Update `autoupdate`
  bucket/tutanota.json
Labels: review-needed

#9581 space-radar: Add version 5.1.0
  bucket/space-radar.json
Labels: review-needed

#9315 renamer: fix persist and pre_install sections
  bucket/renamer.json
Labels: review-needed

#9587 hydrus-network: Fix `autoupdate` & update to version 504
  bucket/hydrus-network.json
Labels: review-needed

#9316 dbvis: Drop 32bit arch, update 64bit url and hash,
  bucket/dbvis.json
Labels: review-needed

#9595 tabby@1.0.185: Fix `post_install` and `autoupdate.hash.url`
  bucket/tabby.json
Labels: manifest-fix-needed

#9592 sfss: Add version 1.0.0
  bucket/sfss.json
Labels: review-needed

#9601 waterfox: Update manifest
  bucket/waterfox.json
Labels: review-needed

#9603 ida-free@8.1: Fix (un)install scripts
  bucket/ida-free.json
Labels: review-needed
