Repository ScoopInstaller/Extras, pull requests merged in 2022-01, with the labels that each got.

#5487 detect-it-easy: Add version 3.03
  bucket/detect-it-easy.json
Labels: review-needed, new package

#3825 docear: Add version 1.2
  bucket/docear.json
Labels: review-needed, new package

#7646 paint.net-plugin-boltbait: Add version 5.1
  bucket/paint.net-plugin-boltbait.json
Labels: review-needed

#7619 youtube-dl-gui@1.8.2: Fix decompress error
  bucket/youtube-dl-gui.json
Labels: review-needed

#5388 portfolio-performance: Add version 0.49.4
  bucket/portfolio-performance.json
Labels: package-fix-needed, review-needed, new package

#7495 RunCat: Add version 1.10
  bucket/runcat.json
Labels: review-needed, upstream, new package

#5538 networkmanager: Add version 2021.1.0
  bucket/networkmanager.json
Labels: package-fix-needed, review-needed, new package

#7647 sozi, inkscape-extension-sozi-extras: Add version 21.12.06
  bucket/inkscape-extension-sozi.json
  bucket/sozi.json
Labels: review-needed

#7650 inkscape, ultravnc, xmind: Change checkver conflicted variable
  bucket/inkscape.json
  bucket/ultravnc.json
  bucket/xmind.json
Labels: review-needed

#4920 speedfan: Use installer
  bucket/speedfan.json
Labels: package improvement

#7651 Librewolf: Add version 95.0.2
  bucket/librewolf.json
Labels: review-needed

#7653 banana-cake-pop: Update to version 1.0.0-preview.18 and fix checkver
  bucket/banana-cake-pop.json
Labels: review-needed

#3439 ontopreplica: Add version 3.5.1-fix
  bucket/ontopreplica.json
Labels: review-needed, new package

#7656 copyq: Update to version 6.0.1
  bucket/copyq.json
Labels: review-needed

#7655 ccextractor: Update to version 0.94
  bucket/ccextractor.json
Labels: review-needed

#7657 dbvis: Update to version 12.1.5 & add autoupdate
  bucket/dbvis.json
Labels: review-needed

#7659 streamlabs-obs: Update to 1.6.4 and fix checkver
  bucket/streamlabs-obs.json
Labels: review-needed

#7660 adwcleaner: Switch to alt checkver URL
  bucket/adwcleaner.json
Labels: review-needed

#7662 kdeconnect: Add version 21.12.0-835
  bucket/kdeconnect.json
Labels: review-needed

#4363 foobar2000(-portable|-encoders): Fix function problems after updating or re-installing, and some improvements
  bucket/foobar2000-encoders.json
  bucket/foobar2000.json
Labels: package-fix-needed, review-needed, package improvement

#7664 chromium: Update to 96.0.4664.93-r929512 and switch to new URL
  bucket/chromium.json
Labels: review-needed

#7668 Add hakchi2 ce
  bucket/hakchi2-ce.json
Labels: review-needed

#7669 captfencoder: Add version 3.1.0
  bucket/captfencoder.json
Labels: review-needed

#7671 trojita: Add version 0.7
  bucket/trojita.json
Labels: review-needed

#7676 Foobar2000: fix conflicts when renaming 'playlists' folder
  bucket/foobar2000.json
Labels: review-needed

#7680 http-downloader@1.0.4.8: Persist "download_history" file
  bucket/http-downloader.json
Labels: review-needed

#7683 ffdec: Add version 15.0.0
  bucket/ffdec.json
Labels: review-needed

#7687 powertoys: Fix installer.script and add au.hash
  bucket/powertoys.json
Labels: review-needed

#7688 advanced-ip-scanner: Add version 2.5.3850
  bucket/advanced-ip-scanner.json
Labels: review-needed

#7694 postman: fix autoupdate
  bucket/postman.json
Labels: review-needed

#7697 siyuan-note: Update to version 1.6.3
  bucket/siyuan-note.json
Labels: review-needed

#6156 imdone: Add version 1.23.2
  bucket/imdone.json
Labels: new package

#7703 masvis: Add version 1.2
  bucket/masvis.json
Labels: review-needed

#7707 yaffplayer: Add version 0.5.7.0
  bucket/yaffplayer.json
Labels: review-needed

#7708 firemin: Add version 8.2.3.5338
  bucket/firemin.json
Labels: review-needed

#7704 openvpn-connect: Add version 3.3.4.2600
  bucket/openvpn-connect.json
Labels: review-needed

#7709 whatsapp: Manually create shortcut w/o junction
  bucket/whatsapp.json
Labels: review-needed

#7705 registryfinder: Add version 2.52
  bucket/registry-finder.json
Labels: review-needed

#7710 modernflyouts: Add version 0.9.3.0
  bucket/modernflyouts.json
Labels: review-needed

#7711 dosbox-staging.json: Add version 0.78.1
  bucket/dosbox-staging.json
Labels: review-needed

#7717 win11dragdroptaskbarfix: add version 2.2.0.0
  bucket/win11dragdroptaskbarfix.json
Labels: review-needed

#7715 webex: Add version 41.12.0.20899
  bucket/webex.json
Labels: review-needed

#7721 add dngrep.json
  bucket/dngrep.json
Labels: review-needed

#7722 opentoonz: add version 1.5.0
  bucket/opentoonz.json
Labels: review-needed

#7714 Flow Launcher: Add version 1.9.1
  bucket/flow-launcher.json
Labels: review-needed

#7725 compactor: Add version 0.10.1
  bucket/compactor.json
Labels: review-needed

#7732 tinymediamanager: Update version to 4.2.5.1, fix checkver url and regex
  bucket/tinymediamanager.json
Labels: review-needed

#7736 autoactions: Update the AutoHDR manifest
  bucket/autoactions.json
  bucket/autohdr.json
Labels: review-needed

#7739 barrier: add version 2.4.0
  bucket/barrier.json
Labels: review-needed

#7738 keenwrite: Add version 2.5.1
  bucket/keenwrite.json
Labels: review-needed

#7744 qview@5.0: Fix extract_dir
  bucket/qview.json
Labels: review-needed

#7748 gcc-arm-none-eabi@10.3-2021.10: update url
  bucket/gcc-arm-none-eabi.json
Labels: review-needed

#7747 godot/godot-mono@3.4.2: moved dl location to github
  bucket/godot-mono.json
  bucket/godot.json
Labels: review-needed

#7752 antimicro: Add pre-install for settings INI file
  bucket/antimicro.json
Labels: review-needed

#7755 beeftext: Add version 13.0
  bucket/beeftext.json
Labels: review-needed

#7735 fatty: Add version 20210122
  bucket/fatty.json
Labels: review-needed

#7760 opentrack: Update to version 2022.1.0
  bucket/opentrack.json
Labels: review-needed

#7759 Macast: Add version 0.7
  bucket/macast.json
Labels: review-needed

#7766 strawberry: Add version 1.0.1 and fix autoupdate
  bucket/strawberry.json
Labels: review-needed

#7765 silex-desktop: add version 2.7.27
  bucket/silex-desktop.json
Labels: review-needed

#7767 Add apkeep
  bucket/apkeep.json
Labels: review-needed

#7774 silex-desktop: add hash extraction
  bucket/silex-desktop.json
Labels: review-needed

#7770 qtemu: Add version 2.1
  bucket/qtemu.json
Labels: review-needed

#7768 virt-viewer: Update to version 11.0-1.0 and add autoupdate
  bucket/virt-viewer.json
Labels: review-needed

#7783 kodi: add hash extraction
  bucket/kodi.json
Labels: review-needed

#7781 skype: Update to version 8.79.0.95 and fix checkver URL
  bucket/skype.json
Labels: review-needed

#7787 postman: fix checkver
  bucket/postman.json
Labels: review-needed

#7790 postman: Use 'nupkg' to simplify script
  bucket/postman.json
Labels: review-needed

#7778 Kryptor: Add version 3.1.0
  bucket/kryptor.json
Labels: review-needed

#7789 Add Password Tech
  bucket/pwtech.json
Labels: review-needed

#7780 rambox-pro: Fix exe name and download link
  bucket/rambox-pro.json
Labels: review-needed

#7791 pure-data: Added version 0.52-1
  bucket/pure-data.json
Labels: review-needed

#7793 megabasterd: Add version 7.49
  bucket/megabasterd.json
Labels: review-needed

#7795 rambox: Rename 'rambox-pro' to 'rambox'
  bucket/rambox-pro.json
  bucket/rambox.json
Labels: review-needed

#7798 webcopy: Remove 'Link Checker' and 'URI Tester'
  bucket/webcopy.json
Labels: review-needed

#7802 MusicPlayer2: Add version 2.73
  bucket/musicplayer2.json
Labels: review-needed

#7804 Vysor: Add version 4.1.77
  bucket/vysor.json
Labels: review-needed

#7807 Notepad3: Update to 5.21.1129.1 & add autoupdate
  bucket/notepad3.json
Labels: review-needed

#7809 mdloader: Add version 1.0.6
  bucket/mdloader.json
Labels: review-needed

#7813 SmartSystemMenu: Add version 2.18.0
  bucket/smartsystemmenu.json
Labels: review-needed

#7816 hydrus-network: update to 470b
  bucket/hydrus-network.json
Labels: review-needed

#7812 KopiaUI: Add version 0.10.1
  bucket/kopiaui.json
Labels: review-needed

#7814 Updated youtube-dl-gui to v1.8.3
  bucket/youtube-dl-gui.json
Labels: review-needed

#7811 Wonderpen: Add version 2.0.5
  bucket/wonderpen.json
Labels: review-needed

#7810 Propertree: Add version 0.2022.01.22
  bucket/propertree.json
Labels: review-needed

#7819 cheat-engine: Undeprecate manifest
  bucket/cheat-engine.json
Labels: review-needed

#7825 FastCopy: update to 4.0.2
  bucket/fastcopy.json
Labels: review-needed

#7831 fastcopy@4.0.2: Fix install scripts
  bucket/fastcopy.json
Labels: review-needed

#7836 Fixed #7835 : Bump storageexplorer to azure-storageexplorer
  bucket/azurestorageexplorer.json
Labels: review-needed

#7848 musicbee: Update manifest
  bucket/musicbee.json
Labels: review-needed

#7840 komorebi: Add version 0.1.8
  bucket/komorebi.json
Labels: review-needed

#7849 fastcopy: Update manifest
  bucket/fastcopy.json
Labels: review-needed

#7858 lenovolegiontoolkit: Add version 1.6.2
  bucket/lenovolegiontoolkit.json
Labels: review-needed

#7834 picgo: Add autoupdate
  bucket/picgo.json
Labels: review-needed

#7863 macast-debug: Add version 0.7
  bucket/macast-debug.json
Labels: review-needed

#7856 xdelta3-cross-gui: Add version 1.1.4
  bucket/xdelta3-cross-gui.json
Labels: review-needed

#7864 sdl2-ttf: Add version 2.0.18
  bucket/sdl2-ttf.json
Labels: review-needed

#7875 postman: fix checkver and update to 9.11.0
  bucket/postman.json
Labels: review-needed

#7880 languagetool: Fix checkverr
  bucket/languagetool.json
Labels: review-needed
