Repository ScoopInstaller/Extras, pull requests merged in 2022-08, with the labels that each got.

#8959 CloudCompare: add version 2.12.4
  bucket/cloudcompare.json
Labels: review-needed

#8970 czkawka-gui: Add version 5.0.0
  bucket/czkawka-gui.json
Labels: review-needed

#8977 masscode: Add version 2.10.0
  bucket/masscode.json
Labels: review-needed

#8979 godot|-mono: Update checkver to rely on GitHub Releases
  bucket/godot-mono.json
  bucket/godot.json
Labels: bug, package update, review-needed

#8978 sysinternals: Use digital version number
  bucket/sysinternals.json
Labels: review-needed

#8980 podman-desktop: Add version 0.0.5
  bucket/podman-desktop.json
Labels: review-needed

#8983 keepass-plugin-keeagent@0.13.1: Fix download URL
  bucket/keepass-plugin-keeagent.json
Labels: review-needed

#8985 ignoreit: Add version 2.4.6
  bucket/ignoreit.json
Labels: review-needed

#8942 crystaldiskinfo: persist AMD_RC2t7 (AMD RAID plugin) DLL files
  bucket/crystaldiskinfo.json
Labels: review-needed

#8948 scoop-completion: add auto-import scripts
  bucket/scoop-completion.json
  scripts/ModifyPSProfile.psm1
  scripts/scoop-completion/append-to-profile.ps1
  scripts/scoop-completion/remove-from-profile.ps1
Labels: review-needed

#8960 F3D: add version 1.2.1
  bucket/f3d.json
Labels: review-needed

#8990 opentabletdriver: Add version 0.6.0.4
  bucket/opentabletdriver.json
Labels: review-needed

#8993 thorium-reader: Add version 2.0.0
  bucket/thorium-reader.json
Labels: review-needed

#8996 publii: Add version 0.40.2
  bucket/publii.json
Labels: review-needed

#8995 komga: Add version 0.157.0
  bucket/komga.json
Labels: review-needed

#8963 divoom-cli, divoom-gateway: Add version 0.1.25
  bucket/divoom-cli.json
  bucket/divoom-gateway.json
Labels: review-needed, discussion

#9003 pet: Add version 0.4.0
  bucket/pet.json
Labels: review-needed

#9007 jaspersoft-studio: Update to version 6.20.0
  bucket/jaspersoft-studio.json
Labels: review-needed

#9009 ytdlp-interface: Add version 1.5.1
  bucket/ytdlp-interface.json
Labels: review-needed

#9005 ezunlock: Add version 0.1
  bucket/ezunlock.json
Labels: review-needed

#9012 ezunlock: fix typo
  bucket/ezunlock.json
Labels: review-needed

#9014 vscodium.json: Add 32bit again
  bucket/vscodium.json
Labels: review-needed

#9023 ignoreit: Update to version 2.4.7
  bucket/ignoreit.json
Labels: review-needed

#9010 paraview: Add version 5.10.1
  bucket/paraview.json
Labels: review-needed

#9015 librewolf: added extra config files to persist, and minor hash fix
  bucket/librewolf.json
Labels: review-needed

#9024 foobar2000-encoders: Fix notes field name
  bucket/foobar2000-encoders.json
Labels: review-needed

#9028 android-messages: Update to 5.3.4
  bucket/android-messages.json
Labels: review-needed

#9031 vscodium: fix autoupdate for 32bit
  bucket/vscodium.json
Labels: review-needed

#9039 asar7z: Add version 1.3
  bucket/asar7z.json
Labels: review-needed

#9040 ddu@18.0.5.4: Hash fix
  bucket/ddu.json
Labels: review-needed

#9044 via: Add license and update install scripts
  bucket/via.json
Labels: review-needed

#9049 gtk-sharp: Add version 2.12.45
  bucket/gtk-sharp.json
Labels: review-needed

#9058 kavita: Add version 0.5.5
  bucket/kavita.json
Labels: review-needed

#9056 vortexdm: Add version 2022.1.0
  bucket/vortexdm.json
Labels: review-needed

#9053 hekasoft-backup-restore: Add version 0.95
  bucket/hekasoft-backup-restore.json
Labels: review-needed

#9067 converseen: Add version 0.9.9.6
  bucket/converseen.json
Labels: review-needed

#9071 legendary: Add version 0.20.27
  bucket/legendary.json
Labels: review-needed

#9072 folder-painter: Add version 1.3
  bucket/folder-painter.json
Labels: review-needed

#9069 konversation: Add version 22.08.0-1220
  bucket/konversation.json
Labels: review-needed

#9064 npiperelay: Add version 0.1.0
  bucket/npiperelay.json
Labels: review-needed

#9079 so: fix autoupdate url
  bucket/so.json
Labels: review-needed

#9095 imo: Update to version 1.4.2.1
  bucket/imo-messenger.json
Labels: review-needed

#9100 hydrus-network@493: change zip name to the qt6 based release
  bucket/hydrus-network.json
Labels: review-needed

#9086 propertree: add persist and shortcut
  bucket/propertree.json
Labels: review-needed

#9083 vortexdm: Update url
  bucket/vortexdm.json
Labels: review-needed

#9085 igdm: Add version 3.0.4
  bucket/igdm.json
Labels: review-needed

#9108 trayweather: Add version 1.24.0
  bucket/trayweather.json
Labels: review-needed

#9094 tanoshi: Add Version 0.29.2
  bucket/tanoshi.json
Labels: review-needed

#9110 Generate PowerShell profile modifier without templete files
  bucket/scoop-completion.json
  scripts/ModifyPSProfile.psm1
  scripts/scoop-completion/append-to-profile.ps1
  scripts/scoop-completion/remove-from-profile.ps1
Labels: review-needed

#9114 vnote: Update to version 3.15.0
  bucket/vnote.json
Labels: review-needed

#9115 webcamoid: Add version 9.0.0
  bucket/webcamoid.json
Labels: review-needed

#9118 sunshine: Fix persist
  bucket/sunshine.json
Labels: review-needed

#9119 weylus: Add version 0.11.4
  bucket/weylus.json
Labels: review-needed

#9104 mangal: add version 3.5.0
  bucket/mangal.json
Labels: review-needed

#9113 mcomix: Update to version v2.0.2
  bucket/mcomix.json
Labels: review-needed

#9133 vnote 3.15.0: fix 64bit url and hash
  bucket/vnote.json
Labels: review-needed

#9120 pia-desktop: Add version 3.3-06906
  bucket/pia-desktop.json
Labels: review-needed

#9130 RatioMaster: Add version 0.43
  bucket/ratiomaster.json
Labels: review-needed
