Repository ScoopInstaller/Extras, pull requests merged in 2023-04, with the labels that each got.

#10895 prusaslicer: Update manifest
  bucket/prusaslicer.json
Labels: review-needed

#10866 wechat: Update Version 3.9.2.23
  bucket/wechat.json
Labels: review-needed

#10874 Update dismplusplus
  bucket/dismplusplus.json
Labels: manifest-fix-needed

#10899 wechat: Fix installation scripts
  bucket/wechat.json
Labels: review-needed

#10330 tailscale: Add note and scripts for adding to startup programs
  bucket/tailscale.json
  scripts/tailscale/add-startup.reg
  scripts/tailscale/remove-startup.reg
Labels: review-needed

#10460 typora: Update description and note
  bucket/typora.json
Labels: review-needed

#10910 vncviewer@7.0.1: Fix url
  bucket/vncviewer.json
Labels: manifest-fix-needed

#10908 cudatext: Update manifest
  bucket/cudatext.json
Labels: review-needed

#10911 antidupl.net@2.3.11: Fix `bin`, `shortcuts`
  bucket/antidupl.net.json
Labels: review-needed

#10579 Kicad@7.0.1: Update manifest to use github release (Closes #10573)
  bucket/kicad.json
  deprecated/kicad-lite.json
Labels: review-needed

#10935 dadroitjsonviewer: Update to version 2.0.1.845 and fix auto-update
  bucket/dadroitjsonviewer.json
Labels: review-needed

#10936 nilesoft-shell: Update to version 1.8.1 and fix autoupdate
  bucket/nilesoft-shell.json
Labels: review-needed

#10929 librewolf: Update to version 111.0.1-1 and fix autoupdate
  bucket/librewolf.json
Labels: review-needed

#10925 chatterino7: Add version 7.4.2
  bucket/chatterino7.json
Labels: review-needed

#10703 USBImager: fixed wrong hash
  bucket/usbimager.json
Labels: review-needed

#10701 Fixed TwitchDownloader Shortcut
  bucket/twitchdownloader.json
Labels: review-needed

#10686 clash-mini: Update to version 0.2.2 & fix autoupdate
  bucket/clash-mini.json
Labels: review-needed

#10687 64gram: Update to version 1.0.70 & drop 32bit support
  bucket/64gram.json
Labels: review-needed

#10688 appflowy: Update to version 0.1.0 & fix autoupdate
  bucket/appflowy.json
Labels: review-needed

#10690 opentrack: Update to 2022.3.2 & fix autoupdate
  bucket/opentrack.json
Labels: review-needed

#10692 ngspice: Update to version 39 & fix autoupdate
  bucket/ngspice.json
Labels: review-needed

#10693 pwsafe: Update to version 3.62.0 & fix autoupdate
  bucket/pwsafe.json
Labels: review-needed

#10655 clash-verge: Add Version 1.2.3
  bucket/clash-verge.json
Labels: review-needed

#10743 vncviewer: Update domain of realvnc
  bucket/vncviewer.json
Labels: review-needed

#10566 vt-uploader: Fix `url`, `hash`, and remove `pre_install`.
  bucket/vt-uploader.json
Labels: review-needed

#10748 azurestorageexplorer@1.28.1 use new naming conventions
  bucket/azurestorageexplorer.json
Labels: review-needed

#10664 twitchdownloader: Fix `shortcuts`, add `persist`
  bucket/twitchdownloader.json
Labels: review-needed

#10799 streamlink: Update to version 5.3.1-1 and fix auto-update
  bucket/streamlink.json
Labels: review-needed

#10939 sweethome3d: fix decompress error
  bucket/sweethome3d.json
Labels: review-needed

#10959 kate: Update to version 22.12.3 and fix autoupdate
  bucket/kate.json
Labels: review-needed

#10960 okular: Update to version 22.12.3 and fix autoupdate
  bucket/okular.json
Labels: review-needed

#10915 Update Powertoys 0.69.0 to use User Installer
  bucket/powertoys.json
Labels: review-needed

#10952 elisa: Update to version 22.12.3 and fix autoupdate
  bucket/elisa.json
Labels: review-needed

#10953 extraterm: Update to version 0.71.0 and fix autoupdate
  bucket/extraterm.json
Labels: review-needed

#10955 filelight: Update to version 22.12.3 and fix autoupdate
  bucket/filelight.json
Labels: review-needed

#10949 cdburnerxp: fix download url & checkver
  bucket/cdburnerxp.json
Labels: review-needed

#10921 v2rayn: *Major* Update to 6.21
  bucket/v2rayn.json
Labels: review-needed

#11006 usbimager: Fix checkver
  bucket/usbimager.json
Labels: review-needed

#11008 xmind: Update to version 22.11.3656 and fix checkver
  bucket/xmind.json
Labels: review-needed

#11004 win-gpg-agent: Remove autoupdate
  bucket/win-gpg-agent.json
Labels: review-needed

#10999 stremio: Update to version 4.4.159 and fix checkver
  bucket/stremio.json
Labels: review-needed

#10994 tomcat: Update checkver
  bucket/tomcat.json
Labels: review-needed

#10993 so: Fix checkver
  bucket/so.json
Labels: review-needed

#10992 saber: Update to version 0.11.4.11040 and fix autoupdate
  bucket/saber.json
Labels: review-needed

#10982 switchhosts: Update to version 4.1.2.6086 and fix autoupdate
  bucket/switchhosts.json
Labels: review-needed

#10980 resource-hacker: Update to version 5.1.7 and fix checkver
  bucket/resource-hacker.json
Labels: review-needed

#10979 pencil: Update to version 3.1.1 & drop 32bit support
  bucket/pencil.json
Labels: review-needed

#10978 prime95: Fix checkver
  bucket/prime95.json
Labels: review-needed

#10977 neovide: Update to version 0.10.4 and fix autoupdate
  bucket/neovide.json
Labels: review-needed

#10974 nheko: Update to version 0.11.3 and fix autoupdate
  bucket/nheko.json
Labels: review-needed

#10973 magicavoxel: Fix checkver
  bucket/magicavoxel.json
Labels: review-needed

#10970 kid3: Update to version 3.9.3-1 and fix checkver
  bucket/kid3.json
Labels: review-needed

#10969 liteide: Update to version 38.2 and drop 32bit support
  bucket/liteide.json
Labels: review-needed

#10968 meshroom: Update to version 2023.1.0 and fix autoupdate
  bucket/meshroom.json
Labels: review-needed

#10967 ios-webkit-debug-proxy: Update to version 1.9.0 and fix autoupdate
  bucket/ios-webkit-debug-proxy.json
Labels: review-needed

#10966 kiwi-for-gmail: Update to version 3.6.2 and fix autoupdate
  bucket/kiwi-for-gmail.json
Labels: review-needed

#10954 coppeliasim: Update to version 4.5.1 and fix autoupdate
  bucket/coppeliasim.json
Labels: review-needed

#10972 mindforger: Fix checkver
  bucket/mindforger.json
Labels: manifest-fix-needed

#10961 autohotkey: Download from Github Release
  bucket/autohotkey.json
Labels: review-needed

#10971 soundswitch: Update to version 6.6.0 & fix autoupdate
  bucket/soundswitch.json
Labels: review-needed

#10981 skype: Update to version 8.96.0.207 and fix checkver
  bucket/skype.json
Labels: review-needed

#10938 postman: Fixing an issue that prevents opening after an update
  bucket/postman.json
Labels: review-needed

#10881 etcher: Update description
  bucket/etcher.json
Labels: review-needed

#11009 pencil: Fix installation
  bucket/pencil.json
Labels: review-needed

#10958 librewolf: Remove ScheduledTask
  bucket/librewolf.json
Labels: review-needed

#10766 yed@3.x: provide jvm options in the start script to fix broken UI rendering
  bucket/yed.json
Labels: review-needed

#10586 musicbee: Update to 3.5.8447 and improve checkver
  bucket/musicbee.json
Labels: review-needed

#10632 musicbee: Add `pre_uninstall` script for manually copying folders, same for the `pre_install` script as well.
  bucket/musicbee.json
Labels: review-needed

#10783 Playnite: add "ExtraMetadata" and "Themes" to persist folders
  bucket/playnite.json
Labels: manifest-fix-needed

#10761 xmind: Update checkver & drop 32bit support
  bucket/xmind.json
Labels: review-needed

#10650 xmousebuttoncontrol: Fix persistence
  bucket/xmousebuttoncontrol.json
Labels: review-needed

#10640 cuetools: update persist options
  bucket/cuetools.json
Labels: review-needed

#10639 virt-viewer: Update checkver
  bucket/virt-viewer.json
Labels: review-needed

#10614 netbeans: update homepage
  bucket/netbeans.json
Labels: review-needed

#10468 foxmail: Add version 7.2.25.213 with new checkver
  bucket/foxmail.json
Labels: review-needed, package-request-needed

#10327 privatezilla: Add scripts download url
  bucket/privatezilla.json
Labels: review-needed

#10600 languagetool: update to windows desktop version 1.0.10
  bucket/languagetool.json
Labels: review-needed

#10582 Freeplane: Update to version 1.10.6u1 & Fix checkver
  bucket/freeplane.json
Labels: manifest-fix-needed

#11011 clash-mini: fix `shortcuts`
  bucket/clash-mini.json
Labels: review-needed

#10276 maple@0.8.1.0: fix path cannot be found error
  bucket/maple.json
Labels: review-needed

#10167 Fix mp3tag json, issue 10166
  bucket/mp3tag.json
Labels: review-needed

#10133 paperwork: Add `architecture`, fixed `url`, fixed `hash`
  bucket/paperwork.json
Labels: review-needed

#10805 robocopy-gui: Use archived link
  bucket/robocopy-gui.json
Labels: review-needed

#11016 umbrello: Update homepage
  bucket/umbrello.json
Labels: review-needed

#11017 chromium: Fix checkver
  bucket/chromium.json
Labels: review-needed

#11018 notesnook: Add arm64 architecture and fix checkver
  bucket/notesnook.json
Labels: review-needed

#11024 textadept: 11.4 fix extract_dir name ".win" vs ".win32"
  bucket/textadept.json
Labels: review-needed

#11025 kopiaui: Fix checkver, update `hash` and `url`, remove `pre_install`
  bucket/kopiaui.json
Labels: review-needed

#10759 firefox-eme-free: Update to version 110.0.1
  bucket/firefox-eme-free.json
Labels: review-needed

#10610 anaconda3: Add tips about 'unable to update pkg' to desc
  bucket/anaconda3.json
Labels: review-needed

#9885 hibit-startup-manager: Add `persist`
  bucket/hibit-startup-manager.json
Labels: review-needed

#11037 synfig-studio: Fix url
  bucket/synfig-studio.json
Labels: review-needed

#11038 imo-messenger: Update to version 1.4.8.3 and fix checkver
  bucket/imo-messenger.json
Labels: review-needed

#11034 jexiftoolgui: Update to version 2.0.2.0 and fix checkver
  bucket/jexiftoolgui.json
Labels: review-needed

#11035 puttie: Update to version 20230219-1bfd0b26 and fix autoupdate
  bucket/puttie.json
Labels: review-needed

#11039 todolist: Fix checkver
  bucket/todolist.json
Labels: review-needed

#11052 librewolf: Update manifest
  bucket/librewolf.json
Labels: review-needed

#11047 smartsvn: Update to version 14.3.0 and fix checkver
  bucket/smartsvn.json
Labels: review-needed

#10922 cryptomator: Add WinFsp as a suggestion/requirement
  bucket/cryptomator.json
Labels: review-needed

#11059 clash.mini(clash-mini): Add version 0.2.2
  bucket/clash.mini.json
Labels: review-needed

#11057 msedgeredirect: Drop architecture select
  bucket/msedgeredirect.json
Labels: review-needed

#11056 3d-fix-manager: Fix download url and homepage
  bucket/3d-fix-manager.json
Labels: review-needed

#11055 pspad: Add 64bit architecture support
  bucket/pspad.json
Labels: review-needed

#11054 fmedia: Update to version 1.30 and fix autoupdate
  bucket/fmedia.json
Labels: review-needed

#4793 seafile-syncing-client: Add version 7.0.9
  bucket/seafile-syncing-client.json
Labels: new package

#9248 SikuliX: Add version 2.0.5
  bucket/sikulix.json
Labels: review-needed

#9286 komf: add version 0.26.0
  bucket/komf.json
Labels: review-needed

#9334 antares: Add version 0.5.17
  bucket/antares.json
Labels: review-needed

#10644 zotero: Added `zotero://` url protocol `post_install` script
  bucket/zotero.json
  scripts/zotero/install-zotero-url-protocol.ps1
  scripts/zotero/uninstall-zotero-url-protocol.ps1
Labels: review-needed

#10526 86Box: Add version 3.11 (+ roms 3.11 + manager 1.7.4)
  bucket/86box-manager.json
  bucket/86box-roms.json
  bucket/86box.json
Labels: review-needed, package-request-needed

#9354 dfu-programmer: Add version 0.7.2
  bucket/dfu-programmer.json
Labels: review-needed

#9352 kotlin-interactive-shell: Add version 0.5.2
  bucket/kotlin-interactive-shell.json
Labels: review-needed

#9340 ludwig: Add version 2.1.1
  bucket/ludwig.json
Labels: review-needed

#11048 pianobar: Add version 2022.10.09
  bucket/pianobar.json
Labels: review-needed

#10901 game-editor: Add version 1.4.0
  bucket/game-editor.json
Labels: review-needed

#10890 mullvad-browser: Add version 12.0.4
  bucket/mullvad-browser.json
Labels: review-needed

#10824 processing4: Add version 1292-4.2
  bucket/processing4.json
Labels: review-needed

#10821 sniffnet: Add version 1.1.2
  bucket/sniffnet.json
Labels: review-needed

#10820 tev: Add version 1.25
  bucket/tev.json
Labels: review-needed

#10798 Add dbxcli 3.0.0
  bucket/dbxcli.json
Labels: review-needed

#10795 raven-reader: Add version 1.0.78
  bucket/raven-reader.json
Labels: review-needed

#10774 lbry: Add version 0.53.9
  bucket/lbry.json
Labels: review-needed

#10780 swyh: Add version 1.5.0
  bucket/swyh.json
Labels: review-needed

#10704 hterm: Add version 0.8.9
  bucket/hterm.json
Labels: review-needed

#10705 tiled: Add version 1.9.2
  bucket/tiled.json
Labels: review-needed

#10734 regiontoshare: Add version 1.3.5651
  bucket/regiontoshare.json
Labels: review-needed

#10736 adventuregamestudio: Add version 3.6.0.47
  bucket/adventuregamestudio.json
Labels: review-needed

#10737 chart-geany: Add version 6.3.2
  bucket/chart-geany.json
Labels: review-needed

#10763 simplyserial: Add version 0.7.0
  bucket/simplyserial.json
Labels: review-needed

#10435 focus: Add version 1.3.0
  bucket/focus.json
Labels: review-needed

#10431 yapa2: Add version 2.0.190
  bucket/yapa.json
  bucket/yapa2.json
Labels: review-needed

#10756 swyh-rs: Add version 1.6.1
  bucket/swyh-rs.json
Labels: review-needed

#10605 xc: Add version 0.0.159
  bucket/xc.json
Labels: review-needed, package-request-needed

#9346 openelement: add version 1.57.R9
  bucket/openelement.json
Labels: review-needed

#9185 xplorer: add version 0.3.1
  bucket/xplorer.json
Labels: not ready

#10564 blobsaver: Add version 3.5.0
  bucket/blobsaver.json
Labels: review-needed

#10569 lark: Add version 6.1.7
  bucket/lark.json
Labels: review-needed

#10818 Add bloop 0.3.3
  bucket/bloop.json
Labels: review-needed

#10924 debugtron: Add version 0.5.0
  bucket/debugtron.json
Labels: review-needed

#10933 marble: Add version 2.2.0
  bucket/marble.json
Labels: review-needed

#10305 magpie: Add version 0.10.1
  bucket/magpie.json
Labels: review-needed

#10137 wavosaur: Add version 1.7.0.0
  bucket/wavosaur.json
Labels: review-needed

#10101 subsync: Add version 0.17.0
  bucket/subsync.json
Labels: review-needed

#10098 labplot: add version 2.10.0
  bucket/labplot.json
Labels: review-needed

#10076 gridplayer: Add version 0.4.3
  bucket/gridplayer.json
Labels: review-needed

#8966 neoray: Add version 0.2.5
  bucket/neoray.json
Labels: not ready

#9732 ahkpm: Add version 0.7.0
  bucket/ahkpm.json
Labels: review-needed

#9720 yuescript: Add version 0.16.1
  bucket/yuescript.json
Labels: review-needed

#9719 avogadro(2): Add manifests
  bucket/avogadro.json
  bucket/avogadro2.json
Labels: review-needed

#9639 volume2: Add version 1.1.7.449
  bucket/volume2.json
Labels: review-needed
