Repository ScoopInstaller/Extras, pull requests merged in 2023-11, with the labels that each got.

#11171 android-sdk: Deprecate manifest
  deprecated/android-sdk.json
Labels: not ready

#11890 mcomix: Update to version 3.0.0, Remove `extract_dir`
  bucket/mcomix.json
Labels: review-needed

#12263 calibre-normal@7.0.0: Path error, unable to install
  bucket/calibre-normal.json
Labels: review-needed

#11970 bruno: add version 1.2.0
  bucket/bruno.json
Labels: review-needed

#12216 mcomix@3.0: Remove trailing commas
  bucket/mcomix.json
Labels: review-needed

#12163 Reaper@7.05: Remove Reamote shim and shortcut
  bucket/reaper.json
Labels: review-needed

#12349 blender-launcher: switch home url
  bucket/blender-launcher.json
Labels: review-needed

#12350 pacaptr: Update to version 0.20.1
  bucket/pacaptr.json
Labels: review-needed

#12333 Fix Converseen checkver
  bucket/converseen.json
Labels: review-needed

#12315 dxwnd@2.06.00: fix the url
  bucket/dxwnd.json
Labels: review-needed

#12008 emule-community@0.70a: fix extract_dir not set to the current version
  bucket/emule-community.json
Labels: review-needed

#11833 taiga: Make `persist` explicit
  bucket/taiga.json
Labels: review-needed

#11849 session@1.11.4: url fix (#11848)
  bucket/session.json
Labels: review-needed

#11865 naps2: Update to version 7.1.2
  bucket/naps2.json
Labels: review-needed

#11887 nilesoft-shell: Fix config file name
  bucket/nilesoft-shell.json
Labels: manifest-fix-needed

#11904 monero: Add `monero-storage` to `persist`
  bucket/monero.json
Labels: review-needed

#11934 Update quiterss.json homepage link
  bucket/quiterss.json
Labels: review-needed

#11952 ddu: Update to version 18.0.6.9
  bucket/ddu.json
Labels: review-needed

#11993 twinkle-tray: Update pre_install scripts
  bucket/twinkle-tray.json
Labels: review-needed

#11998 Update bulk-crap-uninstaller to version 5.7
  bucket/bulk-crap-uninstaller.json
Labels: review-needed

#12006 imagine: Update to Version 1.3.1
  bucket/imagine.json
Labels: review-needed

#12026 neovide@0.11.2: Update links
  bucket/neovide.json
Labels: review-needed

#12029 zaproxy: Update shortcut
  bucket/zaproxy.json
Labels: review-needed

#12045 Update knime.json to 5.1.1 and fix auto-update
  bucket/knime.json
Labels: review-needed

#12047 jellyfin: Update to version 10.8.12 & Fix checkver
  bucket/jellyfin.json
Labels: review-needed

#12056 fluidsynth@2.3.4: Add notes about DLLs
  bucket/fluidsynth.json
Labels: review-needed

#12121 marktext@0.17.1: Update homepage link
  bucket/marktext.json
Labels: review-needed

#12124 sqlitespy: Update to version 1.9.19
  bucket/sqlitespy.json
Labels: review-needed

#12128 teamspeak3: Update to Version 3.6.2
  bucket/teamspeak3.json
Labels: review-needed

#12319 imageglass@9.0.7.1125: Fix manifest for v9
  bucket/imageglass.json
Labels: review-needed

#12251 sumatrapdf@3.5.2: fix current URL SSL error and upgrade package
  bucket/sumatrapdf.json
Labels: review-needed

#12143 appflowy: Update to version 0.3.7 & fix autoupdate
  bucket/appflowy.json
Labels: review-needed

#12099 teraterm@5.0: Switch to github release
  bucket/teraterm.json
Labels: review-needed

#12091 tux-guitar: Fix install on x64, fix malicious homepage url
  bucket/tuxguitar.json
Labels: review-needed

#12101 hysteria: Update to version 2.1.1
  bucket/hysteria.json
Labels: review-needed

#12103 wabt: Fixed shim creation error in 1.0.34
  bucket/wabt.json
Labels: review-needed

#12320 linqpad@8.0.17: Try to fix frequent hash failures
  bucket/linqpad.json
Labels: review-needed

#12280 smplayer@23.6.0.0: Fix autoupdate URLs
  bucket/smplayer.json
Labels: review-needed

#12257 Wireshark@4.0.10: Update wireshark.json for scoop autoupdate to 4.2.0 url.
  bucket/wireshark.json
Labels: review-needed

#12243 resource-hacker: Update URLs to HTTPS
  bucket/resource-hacker.json
Labels: review-needed

#12242 Ngspice: fixed ngspice-41_64.7z hash
  bucket/ngspice.json
Labels: review-needed

#12190 Insomnia@8.3.0: Update license to Apache 2.0
  bucket/insomnia.json
Labels: review-needed

#12159 firefoxpwa: Specify repository for checkver
  bucket/firefoxpwa.json
Labels: review-needed

#12198 steamcmd.json: fix URLs
  bucket/steamcmd.json
Labels: manifest-fix-needed

#12157 vscodium: Update to version 1.84.1.23311, remove 32bit
  bucket/vscodium.json
Labels: review-needed

#12312 focus@1.4.1: Add arm64 version
  bucket/focus.json
Labels: review-needed

#12237 pe-bear: Update to version 0.6.6
  bucket/pe-bear.json
Labels: review-needed

#12185 audacity: Fixes download URLs and updates to version 3.4.1
  bucket/audacity.json
Labels: review-needed

#12247 musikcube: Update to version 3.0.2 and fix autoupdate
  bucket/musikcube.json
Labels: review-needed

#12367 qtemu@2.1: Fix urls
  bucket/qtemu.json
Labels: manifest-fix-needed

#12069 Fix qutebrowser archive extraction
  bucket/qutebrowser.json
Labels: review-needed

#12363 windowsdesktop-runtime@8.0.0: fix description
  bucket/windowsdesktop-runtime.json
Labels: review-needed

#12370 electrum: Update to version 4.4.6 and fix autoupdate
  bucket/electrum.json
Labels: review-needed

#12345 qownnotes@23.11.3: Make a shortcut for the exe directly
  bucket/qownnotes.json
Labels: review-needed

#12378 emeditor: Fix checkver & Update to 23.0.4
  bucket/emeditor.json
Labels: review-needed

#12380 WeChat@3.9.8.15:Update WeChat version to 3.9.8.15
  bucket/wechat.json
Labels: review-needed
