Repository ScoopInstaller/Extras, pull requests merged in 2023-02, with the labels that each got.

#10357 localsend: Add version 1.6.2
  bucket/localsend.json
Labels: review-needed

#10392 ditto: use github releases
  bucket/ditto.json
Labels: review-needed

#10394 kdeconnect: Fix checkver
  bucket/kdeconnect.json
Labels: manifest-fix-needed

#10395 netbeans: Improvement manifest
  bucket/netbeans.json
Labels: review-needed

#10344 rssguard: Fixed checkver and autoupdate properties
  bucket/rssguard.json
Labels: review-needed

#10367 ariang-native: Add Version 1.3.2
  bucket/ariang-native.json
Labels: review-needed

#10458 whkd: Add version 0.1.0
  bucket/whkd.json
Labels: review-needed

#10485 komac: Add version 1.0.1
  bucket/komac.json
Labels: review-needed

#9890 sunshine: Fix installation
  bucket/sunshine.json
  scripts/sunshine/install-service.bat
  scripts/sunshine/uninstall-service.bat
Labels: review-needed

#10492 sunshine: Update `pre_install`
  bucket/sunshine.json
Labels: review-needed

#10285 discrakt: Add version 2.2.4
  bucket/discrakt.json
Labels: review-needed

#10494 ani-cli: Update dependencies, Rearrange fields
  bucket/ani-cli.json
Labels: review-needed

#10491 tinynvidiaupdatechecker: Fix url
  bucket/tinynvidiaupdatechecker.json
Labels: review-needed

#10497 activate-linux: Add version 1.1.0
  bucket/activate-linux.json
Labels: review-needed

#10502 musikcube: Update to version 0.99.5
  bucket/musikcube.json
Labels: review-needed

#10507 dosbox-x: Update to version 2022.12.26, fix autoupdate, add `arm64` arch
  bucket/dosbox-x.json
Labels: review-needed

#10508 transmission: Update to version 4.0.0
  bucket/transmission.json
Labels: review-needed

#10484 fancontrol: Fix `persist`, Arrange & remove unecessary fields, Match latest .NET version
  bucket/fancontrol.json
Labels: review-needed

#10490 usbimager: Add version 1.0.9
  bucket/usbimager.json
Labels: review-needed

#10514 ventoy: Copy altexes to root folder, Fix bin and shortcut, Update hash url
  bucket/ventoy.json
Labels: review-needed

#10481 update capframex to version 1.7.1
  bucket/capframex.json
Labels: review-needed

#10520 saber: Add version 0.9.2.9020
  bucket/saber.json
Labels: review-needed

#10521 butterfly: Add version 1.6.1
  bucket/butterfly.json
Labels: review-needed

#10471 nicotine-plus: Update homepage
  bucket/nicotine-plus.json
Labels: review-needed

#10462 Correct extract_dir value for prusaslicer 2.6.0-alpha3 win64 version
  bucket/prusaslicer.json
Labels: review-needed

#10426 sophiapp: Remove "SophiApp.exe.config" from `persist`
  bucket/sophiapp.json
Labels: review-needed

#10524 glazewm: Add version 1.11.1
  bucket/glazewm.json
Labels: review-needed

#10525 Filezilla
  bucket/filezilla.json
Labels: review-needed

#10552 sublime-merge: Better checkver
  bucket/sublime-merge.json
Labels: review-needed

#10560 chatgpt: Update to version 0.11.0 and fix checkver
  bucket/chatgpt.json
Labels: review-needed

#10565 electronmail: Add version 5.1.3
  bucket/electronmail.json
Labels: review-needed

#10442 obs-studio: Persist and preserve plugins
  bucket/obs-studio.json
Labels: review-needed

#10375 mp3tag: Add 64-bit support
  bucket/mp3tag.json
Labels: review-needed

#10411 libreoffice: Update to version 7.5.1.1
  bucket/libreoffice.json
Labels: review-needed

#10584 sunshine: Update to version 0.18.4, Fix autoupdate
  bucket/sunshine.json
Labels: review-needed

#10555 qq: Add version 9.7.3.28946
  bucket/qq.json
Labels: review-needed, package-request-needed

#10612 icnsify: Add version 2.2.1
  bucket/icnsify.json
Labels: review-needed

#10589 cutter@2.2.0: Fix extract_dir
  bucket/cutter.json
Labels: review-needed

#10628 icnsify: Update to version 2.2.4, Fix urls
  bucket/icnsify.json
Labels: review-needed
