Repository ScoopInstaller/Extras, pull requests merged in 2023-05, with the labels that each got.

#11186 dbvis: Update to version 23.1 and Fix checkver
  bucket/dbvis.json
Labels: review-needed

#11189 dismplusplus@10.1.1002.1B fix version conflict
  bucket/dismplusplus.json
Labels: manifest-fix-needed

#11196 winmerge: Add arm64 architecture
  bucket/winmerge.json
Labels: review-needed

#11188 Add: hideul 1.0
  bucket/hideul.json
Labels: review-needed

#11197 windowsdesktop-runtime: Update manifests
  bucket/windowsdesktop-runtime-lts.json
  bucket/windowsdesktop-runtime.json
Labels: review-needed

#11220 obs-studio: Update to version 29.1 and fix autoupdate
  bucket/obs-studio.json
Labels: review-needed

#11219 kdenlive: Update to version 23.04.0a and fix checkver
  bucket/kdenlive.json
Labels: review-needed

#11218 spotify: Fix installer error
  bucket/spotify.json
Labels: review-needed

#11211 dngrep: Added `pre_uninstall`, edited `persist`, and edited `pre_install`
  bucket/dngrep.json
Labels: review-needed

#11228 rider: Add arm64 support and Switch to zip
  bucket/rider.json
Labels: review-needed

#11238 Add: dn-famitracker 0.5.0.1
  bucket/dn-famitracker.json
Labels: review-needed

#11233 peazip: fix persist configuration
  bucket/peazip.json
Labels: review-needed

#11215 Apifox: Add version 2.2.38
  bucket/apifox.json
Labels: review-needed, verify

#11266 vscodium: Removed 32bit, fixed url's and hash's.
  bucket/vscodium.json
Labels: review-needed

#11251 Add: Icechat 9.53
  bucket/icechat.json
Labels: review-needed

#11263 picocrypt@1.32: fix autoupdate
  bucket/picocrypt.json
Labels: review-needed

#11264 anaconda3: Update to version 2023.03-1 and fix checkver
  bucket/anaconda3.json
Labels: review-needed

#11285 roundedtb: Update `url`, Remove `notes`
  bucket/roundedtb.json
Labels: review-needed

#11294 saber: Update to version 0.12.6
  bucket/saber.json
Labels: review-needed

#11292 obs-studio: Update to version 29.1.1 and fix autoupdate
  bucket/obs-studio.json
Labels: review-needed

#11305 mqttx: Add arm64 architecture
  bucket/mqttx.json
Labels: review-needed

#11303 iphone-sms-backup-and-restore: Fix typos
  bucket/iphone-sms-backup-and-restore.json
Labels: review-needed

#11327 powertoys: Update to version 0.70.0 and add hardlinks
  bucket/powertoys.json
Labels: review-needed

#11326 sidekick-browser@112: updated manifest
  bucket/sidekick-browser.json
Labels: review-needed

#10648 activitywatch: Add version 0.12.1
  bucket/activitywatch.json
Labels: review-needed, not ready

#11335 windows-terminal: Switch to portable distribution
  bucket/windows-terminal.json
Labels: review-needed

#11337 v2rayn: Add `architecture`
  bucket/v2rayn.json
Labels: review-needed

#11348 powertoys: Silently continue when creating hardlinks
  bucket/powertoys.json
Labels: review-needed

#11358 vcredist20(05|08|10|12|13): Update manifest
  bucket/vcredist2005.json
  bucket/vcredist2008.json
  bucket/vcredist2010.json
  bucket/vcredist2012.json
  bucket/vcredist2013.json
Labels: review-needed

#11357 Update vcredist2022 and add autoupdate
  bucket/beebeep.json
  bucket/droidcam.json
  bucket/lively.json
  bucket/sikulix.json
  bucket/trafficmonitor-lite.json
  bucket/trafficmonitor.json
  bucket/vcredist.json
  bucket/vcredist2015.json
  bucket/vcredist2017.json
  bucket/vcredist2019.json
  bucket/vcredist2022.json
  bucket/wingetui.json
Labels: review-needed

#11356 qflipper: Add version 1.3.1
  bucket/qflipper.json
Labels: review-needed

#11366 anaconda3: Fix installation on PowerShell Core(7.x)
  bucket/anaconda3.json
Labels: review-needed

#11368 everything: Check service's BINARY_PATH_NAME
  bucket/everything.json
Labels: review-needed

#11360 avidemux: Fix installation
  bucket/avidemux.json
Labels: review-needed
