Repository ScoopInstaller/Extras, pull requests merged in 2024-02, with the labels that each got.

#12728 labplot: Update to 2.10.1
  bucket/labplot.json
Labels: review-needed

#11956 geode-sdk-cli: Add version 2.7.1
  bucket/geode-sdk-cli.json
Labels: review-needed

#11815 fspy: Add version 1.0.3
  bucket/fspy.json
Labels: review-needed

#12732 otvdm@0.9.0: Fix nested directory installation problem
  bucket/otvdm.json
Labels: review-needed

#12736 gitkraken: Update to version 9.11.1
  bucket/gitkraken.json
Labels: review-needed

#12738 hexo-client@1.3.6: Switch to 64bit version
  bucket/hexo-client.json
Labels: review-needed

#12733 bt@3.7.2: Update persist
  bucket/bt.json
Labels: review-needed

#12740 Gisto: Add version 1.13.4
  bucket/gisto.json
Labels: review-needed

#12272 Lunarvim: Add version 1.3.0
  bucket/lunarvim.json
Labels: review-needed

#12129 i2pd browser: Add version 1.3.3
  bucket/i2pdbrowser.json
Labels: review-needed

#12751 threema: Update to version 1.2.40, fix checkver
  bucket/threema.json
Labels: review-needed

#11751 wxFormBuilder: Add version 4.0.0
  bucket/wxformbuilder.json
Labels: verified, package-request-needed

#12752 dxwnd: Update to version 2.06.02f and fix autoupdate
  bucket/dxwnd.json
Labels: verified

#9511 optimizer: Add version 16.4
  bucket/optimizer.json
Labels: verified, package-request-needed

#9923 clever-ffmpeg: Add version 3.2.3
  bucket/clever-ffmpeg.json
Labels: verified, package-request-needed

#9925 fastflix: Add version 5.2.1
  bucket/fastflix.json
Labels: verified, package-request-needed

#9924 nmkoder: Add version 1.10.0
  bucket/nmkoder.json
Labels: verified, package-request-needed

#11247 free42: Add version 3.1.4
  bucket/free42.json
Labels: verified, review-needed

#12779 ab-av1: Add version 0.7.14
  bucket/ab-av1.json
Labels: verified, review-needed

#12769 ytmdesktop: Update to version 2.0.0, switch to nupkg
  bucket/ytmdesktop.json
Labels: review-needed

#12780 recyclarr: Add version 6.0.2
  bucket/recyclarr.json
Labels: verified

#12761 restic-browser: Add version 0.3.0
  bucket/restic-browser.json
Labels: verified

#11989 swift-mesonlsp: Add version 3.1.3
  bucket/swift-mesonlsp.json
Labels: verified

#11914 gossip: Add version 0.9.0
  bucket/gossip.json
Labels: verified, review-needed

#10048 scrawler: Add version 2024.1.26.0
  bucket/scrawler.json
Labels: verified, review-needed, package-request-needed

#12208 Tomboy-ng: Add version 0.36
  bucket/tomboy-ng.json
Labels: review-needed

#11299 chatall: Add version 1.17.10
  bucket/chatall.json
Labels: review-needed, package-request-needed

#12795 icecast: Update to 2.4.4, fix checkver
  bucket/icecast.json
Labels: review-needed

#11538 hunt-and-peck: Add version 1.7
  bucket/hunt-and-peck.json
Labels: verified, package-request-needed

#12789 rtss@7.3.5: Fix url, hash
  bucket/rtss.json
Labels: review-needed

#12268 blender-benchmark-cli: Add version 3.1.0
  bucket/blender-benchmark-cli.json
Labels: review-needed, package-request-needed

#11770 OpenUtau: Add version 0.1.327
  bucket/openutau.json
Labels: review-needed, package-request-needed

#12805 komorebi@0.1.20: Update notes, bin and suggest
  bucket/komorebi.json
Labels: review-needed

#9658 spyder(-lite): Add version 5.5.1
  bucket/spyder-lite.json
  bucket/spyder.json
Labels: verified

#12810 USBImager@1.0.10: Fix hash
  bucket/usbimager.json
Labels: verified

#12285 sonic-visualiser: Add version 4.5.2
  bucket/sonic-visualiser.json
Labels: review-needed

#12817 miniconda3@23.11.0-2: update url of checkver & hash
  bucket/miniconda3.json
Labels: review-needed

#12786 mediaelch: Add version 2.10.6
  bucket/mediaelch.json
Labels: review-needed

#12827 gptscript: Add version 0.1.1
  bucket/gptscript.json
Labels: review-needed

#12828 lunarvim: Update persist
  bucket/lunarvim.json
Labels: review-needed

#12821 clamav: Add version 1.3.0
  bucket/clamav.json
Labels: verified

#12836 kicad@7.0.11: Fix shortcuts
  bucket/kicad.json
Labels: review-needed

#12839 fwup: Add version 1.10.1
  bucket/fwup.json
Labels: verified

#12835 bzip3: Add version 1.4.0
  bucket/bzip3.json
Labels: verified

#12852 hexchat: Update to version 2.16.2, switch to github releases
  bucket/hexchat.json
Labels: verified

#12758 thorium: Update to version 121.0.6167.204, fix autoupdate & checkver
  bucket/thorium.json
Labels: verified
