Repository ScoopInstaller/Extras, pull requests merged in 2024-04, with the labels that each got.

#11918 tts-voice-wizard: Add version 1.6.7.1
  bucket/tts-voice-wizard.json
Labels: review-needed

#13044 ida-free: Update manifest
  bucket/ida-free.json
Labels: review-needed

#12991 qefi-entry-manager: Add version 0.3.0
  bucket/qefi-entry-manager.json
Labels: review-needed

#13049 umi-ocr: Update to version 2.1.1, fix checkver and autoupdate
  bucket/umi-ocr-paddle.json
  bucket/umi-ocr.json
Labels: review-needed

#13057 vipsdisp: Add version 3.0.4
  bucket/vipsdisp.json
Labels: review-needed

#13066 kodi: Update to version 21.0
  bucket/kodi.json
Labels: review-needed

#13067 vtm: Add version 0.9.77
  bucket/vtm.json
Labels: review-needed

#13060 tts-voice-wizard: update suggested runtime package
  bucket/tts-voice-wizard.json
Labels: review-needed

#13053 helm-ls: Add version 0.0.14
  bucket/helm-ls.json
Labels: review-needed

#13038 keepassxc@2.7.7: Add vcredist suggest
  bucket/keepassxc.json
Labels: review-needed

#13019 gopeed: Add version 1.5.6
  bucket/gopeed.json
Labels: review-needed

#13007 debugviewpp: Add shortcuts
  bucket/debugviewpp.json
Labels: manifest-fix-needed

#12952 uninstalr: Add version 2.3
  bucket/uninstalr.json
Labels: review-needed

#13088 doublecmd: Use portable edition
  bucket/doublecmd.json
Labels: review-needed

#13069 mpc-be@1.7.0: Switch to github releases
  bucket/mpc-be.json
Labels: review-needed

#13086 gnucash: Fix version 5.6
  bucket/gnucash.json
Labels: review-needed

#13100 rio: Add version 0.0.36
  bucket/rio.json
Labels: verified

#13026 Godots: Add version 1.3
  bucket/godots.json
Labels: review-needed

#13102 love@11.5: Fix hash
  bucket/love.json
Labels: review-needed

#13083 ghidra: add GHIDRA_INSTALL_DIR environment variable
  bucket/ghidra.json
Labels: review-needed

#13111 lenovolegiontoolkit@2.21.1: update dotnet dependency
  bucket/lenovolegiontoolkit.json
Labels: review-needed

#13108 attribute-changer: fix notes mismatch with actual files
  bucket/attribute-changer.json
Labels: review-needed

#13131 dbeaver: fix download url
  bucket/dbeaver.json
Labels: review-needed

#13093 gitbutler: Add version 0.11.1
  bucket/gitbutler.json
Labels: review-needed

#13117 CactusViewer: Add version 2.1.4
  bucket/cactusviewer.json
Labels: review-needed

#13141 jetbrains-toolbox@2.3.0.30876: add pre_install to reflect new installer structure of version 2.3
  bucket/jetbrains-toolbox.json
Labels: review-needed

#13151 argyllcms@3.2.0: Remove non-existent bin (spec2cie.exe)
  bucket/argyllcms.json
Labels: review-needed

#13158 autohotkey@2.0.13: Fix pre_uninstall script
  bucket/autohotkey.json
Labels: review-needed

#13122 duckdns: Add version 2.2b
  bucket/duckdns.json
Labels: review-needed

#13090 tsukimi: Add version 0.4.7
  bucket/tsukimi.json
Labels: review-needed

#13106 hourglass-godot: Add version 0.9.4
  bucket/hourglass-godot.json
Labels: review-needed

#13169 komf: make run behaviour same as komga
  bucket/komf.json
Labels: review-needed

#13194 openai-translator: Update to version 0.4.3
  bucket/openai-translator.json
Labels: review-needed

#13104 supermium: Add version 122.0.6261.85
  bucket/supermium.json
Labels: review-needed
