Repository ScoopInstaller/Extras, pull requests merged in 2024-06, with the labels that each got.

#13382 geogebra: Update to version 6.0.843.0
  bucket/geogebra.json
Labels: review-needed

#13344 otadump: Add version 0.1.2
  bucket/otadump.json
Labels: review-needed

#13329 heynote: Add version 1.7.0
  bucket/heynote.json
Labels: review-needed

#12997 alacritty@0.13.2: Add Open with Alacritty context menu
  bucket/alacritty.json
  scripts/alacritty/install-context.reg
  scripts/alacritty/uninstall-context.reg
Labels: review-needed

#13319 orange: Add version 3.36.2
  bucket/orange.json
Labels: review-needed

#13335 neeview: Add version 41.2
  bucket/neeview.json
Labels: review-needed

#13389 picview: Add version 2.2.7
  bucket/picview.json
Labels: review-needed

#13230 owncloud: Add version 5.2.1.13040
  bucket/owncloud.json
Labels: review-needed

#13387 injector: Add version 1.4.0
  bucket/injector.json
Labels: review-needed, package-request-needed

#13426 umi-ocr-paddle@2.1.2: Fix hash
  bucket/umi-ocr-paddle.json
Labels: review-needed

#11837 g-helper: Add version 0.173
  bucket/g-helper.json
Labels: review-needed

#13436 media-downloader: Add version 4.7.0
  bucket/media-downloader.json
Labels: review-needed

#13450 speccy@1.33.75: Fix hash
  bucket/speccy.json
Labels: review-needed

#13214 imageglass: Update to version 9.1.6.14, remove arm64 version
  bucket/imageglass.json
Labels: review-needed

#13465 wait4x: Add version 2.14.1
  bucket/wait4x.json
Labels: verified

#13449 btest: Add version 7.15.1
  bucket/btest.json
Labels: review-needed

#13320 yarr: Add version 2.4
  bucket/yarr.json
Labels: review-needed

#13502 ffmpeg-batch: Update to version 3.0.7, fix autoupdate
  bucket/ffmpeg-batch.json
Labels: review-needed

#13499 buildcache: Update to version 0.30.1, switch to gitlab releases
  bucket/buildcache.json
Labels: review-needed

#12902 clash-nyanpasu: Add Version 1.5.1
  bucket/clash-nyanpasu.json
Labels: review-needed

#13517 librewolf: Remove unnecessary updates files
  bucket/librewolf.json
Labels: review-needed

#13519 horizon-eda@2.6.0: fix shortcut path, remove bin
  bucket/horizon-eda.json
Labels: review-needed

#13406 materialgram: Add version 5.1.7.1
  bucket/materialgram.json
Labels: review-needed

#10339 qucs-s: Add version 24.2.1
  bucket/qucs-s.json
Labels: review-needed
