Repository ScoopInstaller/Extras, pull requests merged in 2024-05, with the labels that each got.

#13175 gitu: Add version 0.19.2
  bucket/gitu.json
Labels: review-needed

#13222 krita@5.2.2: Fix install errors on removing a non-existent file
  bucket/krita.json
Labels: review-needed

#13208 mujoco: Add version 3.1.4
  bucket/mujoco.json
Labels: review-needed

#13058 pkg-config-lite: Add version 0.28-1
  bucket/pkg-config-lite.json
Labels: review-needed

#13242 (chore): Stop removing '*.nsis'
  bucket/android-line-transfer.json
  bucket/android-sms-backup-and-restore.json
  bucket/filezilla-server.json
  bucket/filezilla.json
  bucket/iphone-sms-backup-and-restore.json
  bucket/krita.json
  bucket/lantern-client.json
  bucket/linphone.json
  bucket/linux-reader.json
  bucket/pidgin.json
Labels: review-needed

#13245 7tt: Using extraction instead of portable install
  bucket/7tt.json
Labels: review-needed

#13246 (chore): Replace 'strip_path()' and 'env()' with new functions
  bucket/libsndfile.json
  bucket/raylib-mingw.json
  bucket/raylib.json
  bucket/sdl2-image.json
  bucket/sdl2-mixer.json
  bucket/sdl2-ttf.json
  bucket/sdl2.json
Labels: review-needed

#13257 airdroid: Fixed spelling mistakes in the description property
  bucket/airdroid.json
Labels: review-needed

#13244 GUI.for.Clash: Add version 1.6.7
  bucket/gui-for-clash.json
Labels: review-needed

#13263 redshift-tray: get releases from Codeberg
  bucket/redshift-tray.json
Labels: review-needed

#13241 tsukimi: Update to version 0.4.10 and fix autoupdate
  bucket/tsukimi.json
Labels: review-needed

#13197 stranslate: Add version 1.1.2.509
  bucket/stranslate.json
Labels: review-needed

#13124 beeref: Add version 0.3.3
  bucket/beeref.json
Labels: review-needed

#13297 QuickLook: enable it to call from cli
  bucket/quicklook.json
Labels: review-needed

#13274 theia-ide: Add version 1.49.100
  bucket/theia-ide.json
Labels: review-needed

#13231 plugdata: Add version 0.8.3
  bucket/plugdata.json
Labels: review-needed

#13036 halloy: Add version 2024.7
  bucket/halloy.json
Labels: review-needed

#13264 pipp@2.5.9: Fix urls, disable updates
  bucket/pipp.json
Labels: review-needed

#13325 tidal: Fix preinstall
  bucket/tidal.json
Labels: review-needed

#13328 komorebi: Add komorebi-gui.exe
  bucket/komorebi.json
Labels: review-needed

#13240 cyberchef: Add version 10.18.6
  bucket/cyberchef.json
Labels: verified, review-needed

#13345 pineflash: Add version 0.5.5
  bucket/pineflash.json
Labels: review-needed

#13352 spotube: Update website link
  bucket/spotube.json
Labels: review-needed

#13359 go-chromecast: Add version 0.3.1
  bucket/go-chromecast.json
Labels: review-needed, package-request-needed
