Repository ScoopInstaller/Extras, pull requests merged in 2024-03, with the labels that each got.

#12881 sfsu@1.8.6: Add arm64 arch, use direct exe download urls
  bucket/sfsu.json
Labels: verified

#12890 prusaslicer: Update to version 2.7.2, fix checkver and autoupdate
  bucket/prusaslicer.json
Labels: review-needed

#12868 goldendict@1.5.0: Update homepage, fix checkver and autoupdate
  bucket/goldendict.json
Labels: review-needed

#12876 deeplx: Add version 0.8.8
  bucket/deeplx.json
Labels: verified

#12904 irfanview@4.66: persist Toolbars directory
  bucket/irfanview-lean.json
  bucket/irfanview.json
Labels: review-needed

#12893 sam: Add version 1.5.3.2
  bucket/sam.json
Labels: review-needed

#12879 foxmail@7.2.25.245: Update pre_install script
  bucket/foxmail.json
Labels: review-needed

#12910 adwcleaner: Fix `autoupdate`
  bucket/adwcleaner.json
Labels: review-needed

#12915 czkawka-gui: Update to 7.0.0
  bucket/czkawka-gui.json
Labels: review-needed

#10297 Bforartists: Add version 4.0.2
  bucket/bforartists.json
Labels: review-needed

#12938 foxit-(pdf-)reader: Update to version 2024.1.0
  bucket/foxit-pdf-reader.json
  bucket/foxit-reader.json
Labels: review-needed

#9880 classic-volume-mixer: Add version 2.4
  bucket/classic-volume-mixer.json
Labels: review-needed, package-request-needed

#12941 tidal: Add version 2.36.2
  bucket/tidal.json
Labels: verified

#12948 git-tower@6.0.474: Fix extraction
  bucket/git-tower.json
Labels: review-needed

#12957 Supersonic: Add version 0.9.1
  bucket/supersonic.json
Labels: review-needed

#12959 fancontrol@v183: fix zip name
  bucket/fancontrol.json
Labels: review-needed

#12981 gitify@5.0.0: Fix bundle name
  bucket/gitify.json
Labels: review-needed

#12984 ffmpeg-batch: Update to version 3.0.5, fix autoupdate
  bucket/ffmpeg-batch.json
Labels: review-needed

#11734 affine: Add version 0.13.1
  bucket/affine.json
Labels: review-needed

#12995 sleek@2.0.12: Update download URL
  bucket/sleek.json
Labels: review-needed

#12996 mesonlsp@4.1.3: Rename from swift-mesonlsp to mesonlsp
  bucket/mesonlsp.json
Labels: review-needed

#13010 godot-version-manager: Add version 1.16.1
  bucket/godot-version-manager.json
Labels: review-needed

#13015 yesplaymusic: Update to version 0.4.8, fix autoupdate
  bucket/yesplaymusic.json
Labels: review-needed

#13014 ttdl: Add version 4.2.1
  bucket/ttdl.json
Labels: verified

#13017 gitify@5.1.0: Fix bundle name
  bucket/gitify.json
Labels: review-needed

#13016 clashtui: Update to version 0.2.0
  bucket/clashtui.json
Labels: review-needed

#13021 persepolis: Update to version 4.0.1.0, deprecate 32bit version
  bucket/persepolis.json
Labels: review-needed

#13031 tabby@1.0.207: Fix existing data may be overwritten when update
  bucket/tabby.json
Labels: review-needed
